all:
	g++ -std=c++11 -Wall -Wextra -fsanitize=address,undefined,signed-integer-overflow main.cpp BubbleSort.cpp CountSort.cpp MergeSort.cpp QuickSort.cpp RadixSort.cpp SkipList.cpp Tester.cpp
fast:
	g++ -std=c++11 -O2 main.cpp BubbleSort.cpp CountSort.cpp MergeSort.cpp QuickSort.cpp RadixSort.cpp SkipList.cpp Tester.cpp

clean:
	rm a.out
